name: Release to Vercel

on:
  push:
    branches:
      - master
env:
  CARGO_TERM_COLOR: always
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Vercel-Production-Deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: rustup target add wasm32
        run: rustup target add wasm32-unknown-unknown

      - name: download and run trunk
        run: wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.20.2/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf- && ./trunk build --release

      - name: install vercel
        run: npm install --global vercel@latest

      - name: pull vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: deploy to vercel
        id: deployment
        working-directory: ./dist
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
